name: Band Build

on:
  push:
    branches:
      - main   # change here if you want another branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show current branch
        run: echo Building branch %GITHUB_REF_NAME%

      - name: Check files
        run: dir

      - name: Create build report
        run: echo Empty GitHub Actions build successful > build-report.txt

      - name: Show build report
        run: type build-report.txt